server:
  port: 8888

logging:
  level:
    web: DEBUG

---

spring:
  application:
    name: demo
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password:
  jpa:
    properties:
      hibernate:
        hbm2ddl.auto: update
        show_sql: true
        format_sql: true
        use_sql_comments: true
        #dialect: org.hibernate.dialect.H2Dialect

---
